# Prefix remap
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Colors
set -g default-terminal "screen-256color"

# Mouse
set -g mouse on

# Vi-style motions in copy mode
set -g mode-keys vi

# Splits
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Resize panes with Alt+Arrows
bind -n M-Left resize-pane -L 5
bind -n M-Right resize-pane -R 5
bind -n M-Up resize-pane -U 5
bind -n M-Down resize-pane -D 5
